version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}servicemessage
    build:
      context: .
      dockerfile: service_message/Dockerfile

  client:
    ports:
      - "5001:5173"


  postgres: 
        image: postgres:latest
        environment:
            POSTGRES_DB: messages_go  
            POSTGRES_USER: your_user    
            POSTGRES_PASSWORD: your_password  
        ports:
        - "5432:5432"  
